---
- name: Install Grafana
  hosts: hosts
  become: yes

  tasks:
  - name: download apt key
    ansible.builtin.apt_key:
      url: https://packages.grafana.com/gpg.key
      id: 4E40DDF6D76E284A4A6780E48C8C34C524098CB6      #sudo apt-key list  (remove spaces between)
      state: absent
  - name: add grafana repo to sources.list
    ansible.builtin.apt_repository:
      repo: deb https://packages.grafana.com/oss/deb stable main  #sudo ls /etc/apt/sources.list.d/
      filename: grafana
      state: absent
  - name: update apt cache and install Grafana
    ansible.builtin.apt:
      name: grafana
      state: absent
