---
- name: Install Grafana
  hosts: hosts
  become: yes

  tasks:
  - name: download apt key
    ansible.builtin.apt_key:
      url: https://packages.grafana.com/gpg.key
      state: present
  - name: add grafana repo to sources.list
    ansible.builtin.apt_repository:
      repo: deb https://packages.grafana.com/oss/deb stable main  #sudo ls /etc/apt/sources.list.d/
      filename: grafana                                           #sudo cat /etc/apt/sources.list.d/grafana.list
      state: present
  - name: update apt cache and install Grafana
    ansible.builtin.apt:
      name: grafana                                               #which grafana-server
      update_cache: yes
  - name: ensure Grafana is started and enable
    ansible.builtin.systemd:
      name: grafana-server
      enabled: yes
      state: started                                              #systemctl status grafana-server
